name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Run main help
        run: python3 main.py -h